// Code generated by tools/graphify-fleet/build.py. DO NOT EDIT.
//
// Package fleet is the Graphify-facing map of every agentic and every
// project they have worked. `Worked(agent, project)` calls are the
// extractable edges. Rebuild with: python3 tools/graphify-fleet/build.py
package fleet

// Project is a delivery ship, control-plane repo, or named idea.
type Project struct {
	Slug   string
	Name   string
	Kind   string
	Stage  string
	Access string
}

// Agent is a kernel process or a Cursor cloud run family.
type Agent struct {
	ID   string
	Name string
	Kind string
	Role string
}

// Work is one agent × project edge.
type Work struct {
	Agent   Agent
	Project Project
}

// Edges is every Worked() call recorded at init.
var Edges []Work

// Worked records that agent ran work against project.
// Graphify extracts each call as an edge.
func Worked(agent Agent, project Project) {
	Edges = append(Edges, Work{Agent: agent, Project: project})
}

// cashtro/cashtro
func CashtroProject() Project {
	return Project{Slug: "cashtro", Name: "cashtro/cashtro", Kind: "control-plane", Stage: "active", Access: "ok"}
}

// Evolu-Jeunes/*
func EvoluJeunesProject() Project {
	return Project{Slug: "evolu-jeunes", Name: "Evolu-Jeunes/*", Kind: "org", Stage: "denied", Access: "limited"}
}

// BTK Avocats
func BtkAvocatsProject() Project {
	return Project{Slug: "btk-avocats", Name: "BTK Avocats", Kind: "product", Stage: "production", Access: "catalog-only"}
}

// MD Clinic
func MdClinicProject() Project {
	return Project{Slug: "md-clinic", Name: "MD Clinic", Kind: "product", Stage: "production", Access: "catalog-only"}
}

// Solution Hypothèque QC
func SolutionHypothequeQcProject() Project {
	return Project{Slug: "solution-hypotheque-qc", Name: "Solution Hypothèque QC", Kind: "product", Stage: "production", Access: "catalog-only"}
}

// Éduconnexion
func EduconnexionProject() Project {
	return Project{Slug: "educonnexion", Name: "Éduconnexion", Kind: "product", Stage: "production", Access: "catalog-only"}
}

// Proximity
func ProximityProject() Project {
	return Project{Slug: "proximity", Name: "Proximity", Kind: "product", Stage: "production", Access: "catalog-only"}
}

// ScanApp
func ScanappProject() Project {
	return Project{Slug: "scanapp", Name: "ScanApp", Kind: "product", Stage: "concept", Access: "catalog-only"}
}

// Cashtro delivery catalog
func CashtroCatalogProject() Project {
	return Project{Slug: "cashtro-catalog", Name: "Cashtro delivery catalog", Kind: "product", Stage: "idea", Access: "ok"}
}

// Axel brand AI bot
func AxelProject() Project {
	return Project{Slug: "axel", Name: "Axel brand AI bot", Kind: "idea", Stage: "idea", Access: "named-only"}
}

// Happier non-profit
func HappierProject() Project {
	return Project{Slug: "happier", Name: "Happier non-profit", Kind: "idea", Stage: "idea", Access: "named-only"}
}

// Wealth / trading agents
func WealthProject() Project {
	return Project{Slug: "wealth", Name: "Wealth / trading agents", Kind: "idea", Stage: "idea", Access: "named-only"}
}

// Internal n8n desk
func N8nDeskProject() Project {
	return Project{Slug: "n8n-desk", Name: "Internal n8n desk", Kind: "internal", Stage: "concept", Access: "named-only"}
}

// Kernel agentics registered in internal/agents.
func InitAgent() Agent {
	return Agent{ID: "init", Name: "Init", Kind: "kernel", Role: "kernel"}
}

func DeliveryAgent() Agent {
	return Agent{ID: "delivery", Name: "Delivery", Kind: "kernel", Role: "ship"}
}

func RouterAgent() Agent {
	return Agent{ID: "router", Name: "Router", Kind: "kernel", Role: "model"}
}

func ResearchAgent() Agent {
	return Agent{ID: "research", Name: "Research", Kind: "kernel", Role: "library"}
}

func ExplorerAgent() Agent {
	return Agent{ID: "explorer", Name: "Explorer", Kind: "kernel", Role: "search"}
}

func OperatorAgent() Agent {
	return Agent{ID: "operator", Name: "Operator", Kind: "kernel", Role: "computer-use"}
}

func ReviewerAgent() Agent {
	return Agent{ID: "reviewer", Name: "Reviewer", Kind: "kernel", Role: "qa"}
}

func ArchitectAgent() Agent {
	return Agent{ID: "architect", Name: "Architect", Kind: "kernel", Role: "design"}
}

func DeployAgent() Agent {
	return Agent{ID: "deploy", Name: "Deploy", Kind: "kernel", Role: "release"}
}

func SecurityAgent() Agent {
	return Agent{ID: "security", Name: "Security", Kind: "kernel", Role: "guard"}
}

func MemoryAgent() Agent {
	return Agent{ID: "memory", Name: "Memory", Kind: "kernel", Role: "recall"}
}

func CommsAgent() Agent {
	return Agent{ID: "comms", Name: "Comms", Kind: "kernel", Role: "signal"}
}

func PlannerAgent() Agent {
	return Agent{ID: "planner", Name: "Planner", Kind: "kernel", Role: "backlog"}
}

func InvestigatorAgent() Agent {
	return Agent{ID: "investigator", Name: "Investigator", Kind: "kernel", Role: "incident"}
}

// Cloud run families observed on cashtro/cashtro.
func SecurityReviewOrchestratorAgent() Agent {
	return Agent{ID: "security-review-orchestrator", Name: "Security review orchestrator", Kind: "cloud", Role: "automations"}
}

func PrApprovalAgentAgent() Agent {
	return Agent{ID: "pr-approval-agent", Name: "Pr approval agent", Kind: "cloud", Role: "automations"}
}

func ApiRpcPrivilegeReviewAgent() Agent {
	return Agent{ID: "api-rpc-privilege-review", Name: "API RPC privilege review", Kind: "cloud", Role: "internal"}
}

func ConfigTemplateInjectionReviewAgent() Agent {
	return Agent{ID: "config-template-injection-review", Name: "Config template injection review", Kind: "cloud", Role: "internal"}
}

func PrivacyGuardReviewAAgent() Agent {
	return Agent{ID: "privacy-guard-review-a", Name: "Privacy guard review A", Kind: "cloud", Role: "internal"}
}

func PrivacyGuardReviewBAgent() Agent {
	return Agent{ID: "privacy-guard-review-b", Name: "Privacy guard review B", Kind: "cloud", Role: "internal"}
}

func AgentToolingTrustReviewAgent() Agent {
	return Agent{ID: "agent-tooling-trust-review", Name: "Agent tooling trust review", Kind: "cloud", Role: "internal"}
}

func FilesystemWorkspaceBoundaryAgent() Agent {
	return Agent{ID: "filesystem-workspace-boundary", Name: "Filesystem workspace boundary", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewAAgent() Agent {
	return Agent{ID: "general-security-review-a", Name: "General security review A", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewBAgent() Agent {
	return Agent{ID: "general-security-review-b", Name: "General security review B", Kind: "cloud", Role: "internal"}
}

func AgentToolingTrustBoundaryAgent() Agent {
	return Agent{ID: "agent-tooling-trust-boundary", Name: "Agent tooling trust boundary", Kind: "cloud", Role: "internal"}
}

func FilesystemWorkspaceBoundaryReviewAgent() Agent {
	return Agent{ID: "filesystem-workspace-boundary-review", Name: "Filesystem workspace boundary review", Kind: "cloud", Role: "internal"}
}

func PlatformPatternReviewAAgent() Agent {
	return Agent{ID: "platform-pattern-review-a", Name: "Platform pattern review A", Kind: "cloud", Role: "internal"}
}

func PlatformPatternReviewBAgent() Agent {
	return Agent{ID: "platform-pattern-review-b", Name: "Platform pattern review B", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewRun1Agent() Agent {
	return Agent{ID: "general-security-review-run-1", Name: "General security review run 1", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewRun2Agent() Agent {
	return Agent{ID: "general-security-review-run-2", Name: "General security review run 2", Kind: "cloud", Role: "internal"}
}

func PlatformPatternReviewRun1Agent() Agent {
	return Agent{ID: "platform-pattern-review-run-1", Name: "Platform pattern review run 1", Kind: "cloud", Role: "internal"}
}

func PlatformPatternReviewRun2Agent() Agent {
	return Agent{ID: "platform-pattern-review-run-2", Name: "Platform pattern review run 2", Kind: "cloud", Role: "internal"}
}

func PlatformPatternsReviewAAgent() Agent {
	return Agent{ID: "platform-patterns-review-a", Name: "Platform patterns review A", Kind: "cloud", Role: "internal"}
}

func PlatformPatternsReviewBAgent() Agent {
	return Agent{ID: "platform-patterns-review-b", Name: "Platform patterns review B", Kind: "cloud", Role: "internal"}
}

func PrivacyGuardReviewRun1Agent() Agent {
	return Agent{ID: "privacy-guard-review-run-1", Name: "Privacy guard review run 1", Kind: "cloud", Role: "internal"}
}

func PrivacyGuardReviewRun2Agent() Agent {
	return Agent{ID: "privacy-guard-review-run-2", Name: "Privacy guard review run 2", Kind: "cloud", Role: "internal"}
}

func N90DayWealthPlaybookAgent() Agent {
	return Agent{ID: "90-day-wealth-playbook", Name: "90-day wealth playbook", Kind: "cloud", Role: "internal"}
}

func AgentLoopArchitecturesAgent() Agent {
	return Agent{ID: "agent-loop-architectures", Name: "Agent loop architectures", Kind: "cloud", Role: "internal"}
}

func AiOsDashboardAgent() Agent {
	return Agent{ID: "ai-os-dashboard", Name: "Ai os dashboard", Kind: "cloud", Role: "web"}
}

func ApiRpcPrivilegeReviewerAgent() Agent {
	return Agent{ID: "api-rpc-privilege-reviewer", Name: "API RPC privilege reviewer", Kind: "cloud", Role: "internal"}
}

func AssistantCapabilitiesDefinitionAgent() Agent {
	return Agent{ID: "assistant-capabilities-definition", Name: "Assistant capabilities definition", Kind: "cloud", Role: "web"}
}

func AutonomousWealthAgentsAgent() Agent {
	return Agent{ID: "autonomous-wealth-agents", Name: "Autonomous wealth agents", Kind: "cloud", Role: "web"}
}

func AutonomyGapsInKernelAgent() Agent {
	return Agent{ID: "autonomy-gaps-in-kernel", Name: "Autonomy gaps in kernel", Kind: "cloud", Role: "internal"}
}

func AxelBrandAiBotAgent() Agent {
	return Agent{ID: "axel-brand-ai-bot", Name: "Axel brand ai bot", Kind: "cloud", Role: "web"}
}

func BrowserTestOwnedN8nDeskAgent() Agent {
	return Agent{ID: "browser-test-owned-n8n-desk", Name: "Browser-test owned n8n desk", Kind: "cloud", Role: "internal"}
}

func CashtroKernelExtensionMapAgent() Agent {
	return Agent{ID: "cashtro-kernel-extension-map", Name: "Cashtro kernel extension map", Kind: "cloud", Role: "internal"}
}

func ClaudeCodeSetupInCursorAgent() Agent {
	return Agent{ID: "claude-code-setup-in-cursor", Name: "Claude code setup in cursor", Kind: "cloud", Role: "desktop"}
}

func CloseDeskPulseConfirmFlowAgent() Agent {
	return Agent{ID: "close-desk-pulse-confirm-flow", Name: "Close desk, pulse, confirm flow", Kind: "cloud", Role: "internal"}
}

func CodingAgentProductizationAgent() Agent {
	return Agent{ID: "coding-agent-productization", Name: "Coding agent productization", Kind: "cloud", Role: "internal"}
}

func CompareNicerDeskUisAgent() Agent {
	return Agent{ID: "compare-nicer-desk-uis", Name: "Compare nicer desk UIs", Kind: "cloud", Role: "internal"}
}

func ComputerUsageFeedbackAgent() Agent {
	return Agent{ID: "computer-usage-feedback", Name: "Computer usage feedback", Kind: "cloud", Role: "web"}
}

func ConfigTemplateInjectionReviewerAgent() Agent {
	return Agent{ID: "config-template-injection-reviewer", Name: "Config template injection reviewer", Kind: "cloud", Role: "internal"}
}

func ContentSeoWealthAgentsAgent() Agent {
	return Agent{ID: "content-seo-wealth-agents", Name: "Content SEO wealth agents", Kind: "cloud", Role: "internal"}
}

func DemoDeliveryBoardUiAgent() Agent {
	return Agent{ID: "demo-delivery-board-ui", Name: "Demo delivery board UI", Kind: "cloud", Role: "internal"}
}

func DesignChaNesAgentiquesAgent() Agent {
	return Agent{ID: "design-cha-nes-agentiques", Name: "Design chaînes agentiques", Kind: "cloud", Role: "web"}
}

func DeskPulseWalkthroughAgent() Agent {
	return Agent{ID: "desk-pulse-walkthrough", Name: "Desk pulse walkthrough", Kind: "cloud", Role: "internal"}
}

func DurableCloudRuntimesAgent() Agent {
	return Agent{ID: "durable-cloud-runtimes", Name: "Durable cloud runtimes", Kind: "cloud", Role: "internal"}
}

func ECommerceOpsAgentsAgent() Agent {
	return Agent{ID: "e-commerce-ops-agents", Name: "E-commerce ops agents", Kind: "cloud", Role: "internal"}
}

func ExerciseSymbolsIdeEndToEndAgent() Agent {
	return Agent{ID: "exercise-symbols-ide-end-to-end", Name: "Exercise Symbols IDE end-to-end", Kind: "cloud", Role: "internal"}
}

func ExerciseTeamsBottomDockAgent() Agent {
	return Agent{ID: "exercise-teams-bottom-dock", Name: "Exercise Teams bottom dock", Kind: "cloud", Role: "internal"}
}

func ExerciseUnifiedCashtroDeskAgent() Agent {
	return Agent{ID: "exercise-unified-cashtro-desk", Name: "Exercise unified Cashtro desk", Kind: "cloud", Role: "internal"}
}

func FindAzureKeysInTranscriptsAgent() Agent {
	return Agent{ID: "find-azure-keys-in-transcripts", Name: "Find Azure keys in transcripts", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewerAAgent() Agent {
	return Agent{ID: "general-security-reviewer-a", Name: "General security reviewer A", Kind: "cloud", Role: "internal"}
}

func GeneralSecurityReviewerBAgent() Agent {
	return Agent{ID: "general-security-reviewer-b", Name: "General security reviewer B", Kind: "cloud", Role: "internal"}
}

func GeneralpurposeAgent() Agent {
	return Agent{ID: "generalpurpose", Name: "generalPurpose", Kind: "cloud", Role: "internal"}
}

func GoLanguageTaskAgent() Agent {
	return Agent{ID: "go-language-task", Name: "Go language task", Kind: "cloud", Role: "web"}
}

func GrapiphyAgentProjectScopeAgent() Agent {
	return Agent{ID: "grapiphy-agent-project-scope", Name: "Grapiphy agent project scope", Kind: "cloud", Role: "web"}
}

func HappierNonProfitProgramInfoAgent() Agent {
	return Agent{ID: "happier-non-profit-program-info", Name: "Happier non-profit program info", Kind: "cloud", Role: "web"}
}

func InternalN8nWorkflowAgent() Agent {
	return Agent{ID: "internal-n8n-workflow", Name: "Internal n8n workflow", Kind: "cloud", Role: "web"}
}

func KimmyK3GlmWealthAgent() Agent {
	return Agent{ID: "kimmy-k3-glm-wealth", Name: "Kimmy k3 glm wealth", Kind: "cloud", Role: "web"}
}

func LeadGenSalesAgentsAgent() Agent {
	return Agent{ID: "lead-gen-sales-agents", Name: "Lead gen sales agents", Kind: "cloud", Role: "internal"}
}

func LinkForUsageAgent() Agent {
	return Agent{ID: "link-for-usage", Name: "Link for usage", Kind: "cloud", Role: "web"}
}

func MapCashtroOsCodeAgent() Agent {
	return Agent{ID: "map-cashtro-os-code", Name: "Map Cashtro OS code", Kind: "cloud", Role: "internal"}
}

func McpMarketplacesDistributionAgent() Agent {
	return Agent{ID: "mcp-marketplaces-distribution", Name: "MCP marketplaces distribution", Kind: "cloud", Role: "internal"}
}

func McpProtocolDesignAgent() Agent {
	return Agent{ID: "mcp-protocol-design", Name: "MCP protocol design", Kind: "cloud", Role: "internal"}
}

func MemoryAndLearningLoopsAgent() Agent {
	return Agent{ID: "memory-and-learning-loops", Name: "Memory and learning loops", Kind: "cloud", Role: "internal"}
}

func MultiAgentSwarmDeliveryAgent() Agent {
	return Agent{ID: "multi-agent-swarm-delivery", Name: "Multi-agent swarm delivery", Kind: "cloud", Role: "internal"}
}

func NamingSchemeRevisionAgent() Agent {
	return Agent{ID: "naming-scheme-revision", Name: "Naming scheme revision", Kind: "cloud", Role: "web"}
}

func OpenSourceAgentStacksAgent() Agent {
	return Agent{ID: "open-source-agent-stacks", Name: "Open source agent stacks", Kind: "cloud", Role: "internal"}
}

func PaymentAndBillingRailsAgent() Agent {
	return Agent{ID: "payment-and-billing-rails", Name: "Payment and billing rails", Kind: "cloud", Role: "internal"}
}

func PrivacyGuardReviewRetryAgent() Agent {
	return Agent{ID: "privacy-guard-review-retry", Name: "Privacy guard review retry", Kind: "cloud", Role: "internal"}
}

func ResearchAiOsPatternsAgent() Agent {
	return Agent{ID: "research-ai-os-patterns", Name: "Research AI OS patterns", Kind: "cloud", Role: "internal"}
}

func ResearchArbitrageAgentsAgent() Agent {
	return Agent{ID: "research-arbitrage-agents", Name: "Research arbitrage agents", Kind: "cloud", Role: "internal"}
}

func ReviewChooserWalkthroughVideoAgent() Agent {
	return Agent{ID: "review-chooser-walkthrough-video", Name: "Review chooser walkthrough video", Kind: "cloud", Role: "internal"}
}

func ReviewClosedHoursDemoVideoAgent() Agent {
	return Agent{ID: "review-closed-hours-demo-video", Name: "Review closed-hours demo video", Kind: "cloud", Role: "internal"}
}

func ReviewCompressedNightShiftDemoAgent() Agent {
	return Agent{ID: "review-compressed-night-shift-demo", Name: "Review compressed night-shift demo", Kind: "cloud", Role: "internal"}
}

func ReviewGiantDeskVideoAgent() Agent {
	return Agent{ID: "review-giant-desk-video", Name: "Review Giant desk video", Kind: "cloud", Role: "internal"}
}

func ReviewLautaroDeskVideoAgent() Agent {
	return Agent{ID: "review-lautaro-desk-video", Name: "Review Lautaro desk video", Kind: "cloud", Role: "internal"}
}

func ReviewNamingDeskWalkthroughVideoAgent() Agent {
	return Agent{ID: "review-naming-desk-walkthrough-video", Name: "Review naming desk walkthrough video", Kind: "cloud", Role: "internal"}
}

func ReviewSymbolsIdeWalkthroughVideoAgent() Agent {
	return Agent{ID: "review-symbols-ide-walkthrough-video", Name: "Review Symbols IDE walkthrough video", Kind: "cloud", Role: "internal"}
}

func ReviewTeamsDockDemoVideoAgent() Agent {
	return Agent{ID: "review-teams-dock-demo-video", Name: "Review Teams dock demo video", Kind: "cloud", Role: "internal"}
}

func ReviewVoltronDeskDemoAgent() Agent {
	return Agent{ID: "review-voltron-desk-demo", Name: "Review Voltron desk demo", Kind: "cloud", Role: "internal"}
}

func SaasAiOsDashboardAgent() Agent {
	return Agent{ID: "saas-ai-os-dashboard", Name: "Saas ai os dashboard", Kind: "cloud", Role: "web"}
}

func SaasProductizedAgentsAgent() Agent {
	return Agent{ID: "saas-productized-agents", Name: "SaaS productized agents", Kind: "cloud", Role: "internal"}
}

func SafetyGovernanceAutonomyAgent() Agent {
	return Agent{ID: "safety-governance-autonomy", Name: "Safety governance autonomy", Kind: "cloud", Role: "internal"}
}

func ScanAppReadinessAgent() Agent {
	return Agent{ID: "scan-app-readiness", Name: "Scan app readiness", Kind: "cloud", Role: "web"}
}

func SkillFilesAsProductsAgent() Agent {
	return Agent{ID: "skill-files-as-products", Name: "Skill files as products", Kind: "cloud", Role: "internal"}
}

func SummarizeClosedHoursAgentAgent() Agent {
	return Agent{ID: "summarize-closed-hours-agent", Name: "Summarize closed-hours agent", Kind: "cloud", Role: "internal"}
}

func SummarizeKernelOsTranscriptsAgent() Agent {
	return Agent{ID: "summarize-kernel-os-transcripts", Name: "Summarize kernel+OS transcripts", Kind: "cloud", Role: "internal"}
}

func SummarizePriorCashtroAgentAgent() Agent {
	return Agent{ID: "summarize-prior-cashtro-agent", Name: "Summarize prior Cashtro agent", Kind: "cloud", Role: "internal"}
}

func SummarizeSwarmDesignNotesAgent() Agent {
	return Agent{ID: "summarize-swarm-design-notes", Name: "Summarize swarm design notes", Kind: "cloud", Role: "internal"}
}

func SummarizeVideoReviewAgentAgent() Agent {
	return Agent{ID: "summarize-video-review-agent", Name: "Summarize video review agent", Kind: "cloud", Role: "internal"}
}

func SummarizeWealthDashboardTranscriptsAgent() Agent {
	return Agent{ID: "summarize-wealth-dashboard-transcripts", Name: "Summarize wealth+dashboard transcripts", Kind: "cloud", Role: "internal"}
}

func SuperMemoryProblemSolvingAgent() Agent {
	return Agent{ID: "super-memory-problem-solving", Name: "Super memory problem solving", Kind: "cloud", Role: "web"}
}

func TeamsConversationAiProximityAgent() Agent {
	return Agent{ID: "teams-conversation-ai-proximity", Name: "Teams conversation ai proximity", Kind: "cloud", Role: "web"}
}

func TestAiOsChooserDeskAgent() Agent {
	return Agent{ID: "test-ai-os-chooser-desk", Name: "Test AI OS chooser desk", Kind: "cloud", Role: "internal"}
}

func TradingAiMoneyGenerationAgent() Agent {
	return Agent{ID: "trading-ai-money-generation", Name: "Trading ai money generation", Kind: "cloud", Role: "web"}
}

func UnclearTaskSubjectAgent() Agent {
	return Agent{ID: "unclear-task-subject", Name: "Unclear task subject", Kind: "cloud", Role: "web"}
}

func VerifyClosedHoursNightShiftAgent() Agent {
	return Agent{ID: "verify-closed-hours-night-shift", Name: "Verify closed-hours night shift", Kind: "cloud", Role: "internal"}
}

func VerifyLautaroBuilderCreatorDeskAgent() Agent {
	return Agent{ID: "verify-lautaro-builder-creator-desk", Name: "Verify Lautaro Builder Creator desk", Kind: "cloud", Role: "internal"}
}

func VerifyVoltronDeskDesktopMobileAgent() Agent {
	return Agent{ID: "verify-voltron-desk-desktop-mobile", Name: "Verify Voltron desk desktop+mobile", Kind: "cloud", Role: "internal"}
}

func VoltronContinuousOperationAgent() Agent {
	return Agent{ID: "voltron-continuous-operation", Name: "Voltron continuous operation", Kind: "cloud", Role: "web"}
}

func WordpressClientFactoryAgent() Agent {
	return Agent{ID: "wordpress-client-factory", Name: "WordPress client factory", Kind: "cloud", Role: "internal"}
}

func ZappierIntegrationAgent() Agent {
	return Agent{ID: "zappier-integration", Name: "Zappier integration", Kind: "cloud", Role: "web"}
}

func init() {
	Worked(InitAgent(), CashtroProject())                                    // Boots the OS and publishes the manifesto.
	Worked(DeliveryAgent(), CashtroProject())                                // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), CashtroCatalogProject())                         // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), BtkAvocatsProject())                             // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), MdClinicProject())                               // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), SolutionHypothequeQcProject())                   // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), EduconnexionProject())                           // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), ProximityProject())                              // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), ScanappProject())                                // Owns the idea → concept → production line.
	Worked(DeliveryAgent(), CashtroCatalogProject())                         // Owns the idea → concept → production line.
	Worked(RouterAgent(), CashtroProject())                                  // Optional OpenRouter model bus.
	Worked(ResearchAgent(), CashtroProject())                                // Ingests sourced findings into notes.
	Worked(ExplorerAgent(), CashtroProject())                                // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), BtkAvocatsProject())                             // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), MdClinicProject())                               // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), SolutionHypothequeQcProject())                   // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), EduconnexionProject())                           // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), ProximityProject())                              // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), ScanappProject())                                // Searches processes, ships, and notes.
	Worked(ExplorerAgent(), CashtroCatalogProject())                         // Searches processes, ships, and notes.
	Worked(OperatorAgent(), CashtroProject())                                // Browser and desktop for shippers.
	Worked(ReviewerAgent(), CashtroProject())                                // Reads walkthrough artifacts before a ship is done.
	Worked(ArchitectAgent(), CashtroProject())                               // Shapes apps and workflows before they hit the line.
	Worked(DeployAgent(), CashtroProject())                                  // CI, preview, and production promotion.
	Worked(SecurityAgent(), CashtroProject())                                // Triage CVE and SAST findings.
	Worked(MemoryAgent(), CashtroProject())                                  // Episodic store and recall.
	Worked(CommsAgent(), CashtroProject())                                   // Outbound only after a human confirm.
	Worked(PlannerAgent(), CashtroProject())                                 // Turns a goal into idea-stage ships.
	Worked(PlannerAgent(), CashtroCatalogProject())                          // Turns a goal into idea-stage ships.
	Worked(InvestigatorAgent(), CashtroProject())                            // Traces a failing check to blast radius.
	Worked(SecurityReviewOrchestratorAgent(), CashtroProject())              // Security review orchestrator
	Worked(PrApprovalAgentAgent(), CashtroProject())                         // Pr approval agent
	Worked(ApiRpcPrivilegeReviewAgent(), CashtroProject())                   // API RPC privilege review
	Worked(ConfigTemplateInjectionReviewAgent(), CashtroProject())           // Config template injection review
	Worked(PrivacyGuardReviewAAgent(), CashtroProject())                     // Privacy guard review A
	Worked(PrivacyGuardReviewBAgent(), CashtroProject())                     // Privacy guard review B
	Worked(AgentToolingTrustReviewAgent(), CashtroProject())                 // Agent tooling trust review
	Worked(FilesystemWorkspaceBoundaryAgent(), CashtroProject())             // Filesystem workspace boundary
	Worked(GeneralSecurityReviewAAgent(), CashtroProject())                  // General security review A
	Worked(GeneralSecurityReviewBAgent(), CashtroProject())                  // General security review B
	Worked(AgentToolingTrustBoundaryAgent(), CashtroProject())               // Agent tooling trust boundary
	Worked(FilesystemWorkspaceBoundaryReviewAgent(), CashtroProject())       // Filesystem workspace boundary review
	Worked(PlatformPatternReviewAAgent(), CashtroProject())                  // Platform pattern review A
	Worked(PlatformPatternReviewBAgent(), CashtroProject())                  // Platform pattern review B
	Worked(GeneralSecurityReviewRun1Agent(), CashtroProject())               // General security review run 1
	Worked(GeneralSecurityReviewRun2Agent(), CashtroProject())               // General security review run 2
	Worked(PlatformPatternReviewRun1Agent(), CashtroProject())               // Platform pattern review run 1
	Worked(PlatformPatternReviewRun2Agent(), CashtroProject())               // Platform pattern review run 2
	Worked(PlatformPatternsReviewAAgent(), CashtroProject())                 // Platform patterns review A
	Worked(PlatformPatternsReviewBAgent(), CashtroProject())                 // Platform patterns review B
	Worked(PrivacyGuardReviewRun1Agent(), CashtroProject())                  // Privacy guard review run 1
	Worked(PrivacyGuardReviewRun2Agent(), CashtroProject())                  // Privacy guard review run 2
	Worked(N90DayWealthPlaybookAgent(), CashtroProject())                    // 90-day wealth playbook
	Worked(N90DayWealthPlaybookAgent(), WealthProject())                     // 90-day wealth playbook
	Worked(AgentLoopArchitecturesAgent(), CashtroProject())                  // Agent loop architectures
	Worked(AiOsDashboardAgent(), CashtroProject())                           // Ai os dashboard
	Worked(AiOsDashboardAgent(), CashtroCatalogProject())                    // Ai os dashboard
	Worked(ApiRpcPrivilegeReviewerAgent(), CashtroProject())                 // API RPC privilege reviewer
	Worked(AssistantCapabilitiesDefinitionAgent(), CashtroProject())         // Assistant capabilities definition
	Worked(AutonomousWealthAgentsAgent(), CashtroProject())                  // Autonomous wealth agents
	Worked(AutonomousWealthAgentsAgent(), WealthProject())                   // Autonomous wealth agents
	Worked(AutonomyGapsInKernelAgent(), CashtroProject())                    // Autonomy gaps in kernel
	Worked(AxelBrandAiBotAgent(), CashtroProject())                          // Axel brand ai bot
	Worked(AxelBrandAiBotAgent(), AxelProject())                             // Axel brand ai bot
	Worked(BrowserTestOwnedN8nDeskAgent(), CashtroProject())                 // Browser-test owned n8n desk
	Worked(BrowserTestOwnedN8nDeskAgent(), N8nDeskProject())                 // Browser-test owned n8n desk
	Worked(BrowserTestOwnedN8nDeskAgent(), CashtroCatalogProject())          // Browser-test owned n8n desk
	Worked(CashtroKernelExtensionMapAgent(), CashtroProject())               // Cashtro kernel extension map
	Worked(ClaudeCodeSetupInCursorAgent(), CashtroProject())                 // Claude code setup in cursor
	Worked(CloseDeskPulseConfirmFlowAgent(), CashtroProject())               // Close desk, pulse, confirm flow
	Worked(CloseDeskPulseConfirmFlowAgent(), CashtroCatalogProject())        // Close desk, pulse, confirm flow
	Worked(CodingAgentProductizationAgent(), CashtroProject())               // Coding agent productization
	Worked(CompareNicerDeskUisAgent(), CashtroProject())                     // Compare nicer desk UIs
	Worked(CompareNicerDeskUisAgent(), CashtroCatalogProject())              // Compare nicer desk UIs
	Worked(ComputerUsageFeedbackAgent(), CashtroProject())                   // Computer usage feedback
	Worked(ConfigTemplateInjectionReviewerAgent(), CashtroProject())         // Config template injection reviewer
	Worked(ContentSeoWealthAgentsAgent(), CashtroProject())                  // Content SEO wealth agents
	Worked(ContentSeoWealthAgentsAgent(), WealthProject())                   // Content SEO wealth agents
	Worked(DemoDeliveryBoardUiAgent(), CashtroProject())                     // Demo delivery board UI
	Worked(DesignChaNesAgentiquesAgent(), CashtroProject())                  // Design chaînes agentiques
	Worked(DeskPulseWalkthroughAgent(), CashtroProject())                    // Desk pulse walkthrough
	Worked(DeskPulseWalkthroughAgent(), CashtroCatalogProject())             // Desk pulse walkthrough
	Worked(DurableCloudRuntimesAgent(), CashtroProject())                    // Durable cloud runtimes
	Worked(ECommerceOpsAgentsAgent(), CashtroProject())                      // E-commerce ops agents
	Worked(ExerciseSymbolsIdeEndToEndAgent(), CashtroProject())              // Exercise Symbols IDE end-to-end
	Worked(ExerciseTeamsBottomDockAgent(), CashtroProject())                 // Exercise Teams bottom dock
	Worked(ExerciseUnifiedCashtroDeskAgent(), CashtroProject())              // Exercise unified Cashtro desk
	Worked(ExerciseUnifiedCashtroDeskAgent(), CashtroCatalogProject())       // Exercise unified Cashtro desk
	Worked(FindAzureKeysInTranscriptsAgent(), CashtroProject())              // Find Azure keys in transcripts
	Worked(GeneralSecurityReviewerAAgent(), CashtroProject())                // General security reviewer A
	Worked(GeneralSecurityReviewerBAgent(), CashtroProject())                // General security reviewer B
	Worked(GeneralpurposeAgent(), CashtroProject())                          // generalPurpose
	Worked(GoLanguageTaskAgent(), CashtroProject())                          // Go language task
	Worked(GrapiphyAgentProjectScopeAgent(), CashtroProject())               // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), BtkAvocatsProject())            // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), MdClinicProject())              // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), SolutionHypothequeQcProject())  // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), EduconnexionProject())          // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), ProximityProject())             // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), ScanappProject())               // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), CashtroCatalogProject())        // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), EvoluJeunesProject())           // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), AxelProject())                  // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), HappierProject())               // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), WealthProject())                // Grapiphy agent project scope
	Worked(GrapiphyAgentProjectScopeAgent(), N8nDeskProject())               // Grapiphy agent project scope
	Worked(HappierNonProfitProgramInfoAgent(), CashtroProject())             // Happier non-profit program info
	Worked(HappierNonProfitProgramInfoAgent(), HappierProject())             // Happier non-profit program info
	Worked(InternalN8nWorkflowAgent(), CashtroProject())                     // Internal n8n workflow
	Worked(InternalN8nWorkflowAgent(), N8nDeskProject())                     // Internal n8n workflow
	Worked(KimmyK3GlmWealthAgent(), CashtroProject())                        // Kimmy k3 glm wealth
	Worked(KimmyK3GlmWealthAgent(), WealthProject())                         // Kimmy k3 glm wealth
	Worked(LeadGenSalesAgentsAgent(), CashtroProject())                      // Lead gen sales agents
	Worked(LinkForUsageAgent(), CashtroProject())                            // Link for usage
	Worked(MapCashtroOsCodeAgent(), CashtroProject())                        // Map Cashtro OS code
	Worked(McpMarketplacesDistributionAgent(), CashtroProject())             // MCP marketplaces distribution
	Worked(McpProtocolDesignAgent(), CashtroProject())                       // MCP protocol design
	Worked(MemoryAndLearningLoopsAgent(), CashtroProject())                  // Memory and learning loops
	Worked(MultiAgentSwarmDeliveryAgent(), CashtroProject())                 // Multi-agent swarm delivery
	Worked(NamingSchemeRevisionAgent(), CashtroProject())                    // Naming scheme revision
	Worked(OpenSourceAgentStacksAgent(), CashtroProject())                   // Open source agent stacks
	Worked(PaymentAndBillingRailsAgent(), CashtroProject())                  // Payment and billing rails
	Worked(PrivacyGuardReviewRetryAgent(), CashtroProject())                 // Privacy guard review retry
	Worked(ResearchAiOsPatternsAgent(), CashtroProject())                    // Research AI OS patterns
	Worked(ResearchAiOsPatternsAgent(), CashtroCatalogProject())             // Research AI OS patterns
	Worked(ResearchArbitrageAgentsAgent(), CashtroProject())                 // Research arbitrage agents
	Worked(ReviewChooserWalkthroughVideoAgent(), CashtroProject())           // Review chooser walkthrough video
	Worked(ReviewClosedHoursDemoVideoAgent(), CashtroProject())              // Review closed-hours demo video
	Worked(ReviewCompressedNightShiftDemoAgent(), CashtroProject())          // Review compressed night-shift demo
	Worked(ReviewGiantDeskVideoAgent(), CashtroProject())                    // Review Giant desk video
	Worked(ReviewGiantDeskVideoAgent(), CashtroCatalogProject())             // Review Giant desk video
	Worked(ReviewLautaroDeskVideoAgent(), CashtroProject())                  // Review Lautaro desk video
	Worked(ReviewLautaroDeskVideoAgent(), CashtroCatalogProject())           // Review Lautaro desk video
	Worked(ReviewNamingDeskWalkthroughVideoAgent(), CashtroProject())        // Review naming desk walkthrough video
	Worked(ReviewNamingDeskWalkthroughVideoAgent(), CashtroCatalogProject()) // Review naming desk walkthrough video
	Worked(ReviewSymbolsIdeWalkthroughVideoAgent(), CashtroProject())        // Review Symbols IDE walkthrough video
	Worked(ReviewTeamsDockDemoVideoAgent(), CashtroProject())                // Review Teams dock demo video
	Worked(ReviewVoltronDeskDemoAgent(), CashtroProject())                   // Review Voltron desk demo
	Worked(ReviewVoltronDeskDemoAgent(), CashtroCatalogProject())            // Review Voltron desk demo
	Worked(SaasAiOsDashboardAgent(), CashtroProject())                       // Saas ai os dashboard
	Worked(SaasAiOsDashboardAgent(), CashtroCatalogProject())                // Saas ai os dashboard
	Worked(SaasProductizedAgentsAgent(), CashtroProject())                   // SaaS productized agents
	Worked(SafetyGovernanceAutonomyAgent(), CashtroProject())                // Safety governance autonomy
	Worked(ScanAppReadinessAgent(), CashtroProject())                        // Scan app readiness
	Worked(ScanAppReadinessAgent(), ScanappProject())                        // Scan app readiness
	Worked(SkillFilesAsProductsAgent(), CashtroProject())                    // Skill files as products
	Worked(SummarizeClosedHoursAgentAgent(), CashtroProject())               // Summarize closed-hours agent
	Worked(SummarizeKernelOsTranscriptsAgent(), CashtroProject())            // Summarize kernel+OS transcripts
	Worked(SummarizePriorCashtroAgentAgent(), CashtroProject())              // Summarize prior Cashtro agent
	Worked(SummarizeSwarmDesignNotesAgent(), CashtroProject())               // Summarize swarm design notes
	Worked(SummarizeVideoReviewAgentAgent(), CashtroProject())               // Summarize video review agent
	Worked(SummarizeWealthDashboardTranscriptsAgent(), CashtroProject())     // Summarize wealth+dashboard transcripts
	Worked(SummarizeWealthDashboardTranscriptsAgent(), WealthProject())      // Summarize wealth+dashboard transcripts
	Worked(SuperMemoryProblemSolvingAgent(), CashtroProject())               // Super memory problem solving
	Worked(TeamsConversationAiProximityAgent(), CashtroProject())            // Teams conversation ai proximity
	Worked(TeamsConversationAiProximityAgent(), ProximityProject())          // Teams conversation ai proximity
	Worked(TestAiOsChooserDeskAgent(), CashtroProject())                     // Test AI OS chooser desk
	Worked(TestAiOsChooserDeskAgent(), CashtroCatalogProject())              // Test AI OS chooser desk
	Worked(TradingAiMoneyGenerationAgent(), CashtroProject())                // Trading ai money generation
	Worked(TradingAiMoneyGenerationAgent(), WealthProject())                 // Trading ai money generation
	Worked(UnclearTaskSubjectAgent(), CashtroProject())                      // Unclear task subject
	Worked(VerifyClosedHoursNightShiftAgent(), CashtroProject())             // Verify closed-hours night shift
	Worked(VerifyLautaroBuilderCreatorDeskAgent(), CashtroProject())         // Verify Lautaro Builder Creator desk
	Worked(VerifyLautaroBuilderCreatorDeskAgent(), CashtroCatalogProject())  // Verify Lautaro Builder Creator desk
	Worked(VerifyVoltronDeskDesktopMobileAgent(), CashtroProject())          // Verify Voltron desk desktop+mobile
	Worked(VerifyVoltronDeskDesktopMobileAgent(), CashtroCatalogProject())   // Verify Voltron desk desktop+mobile
	Worked(VoltronContinuousOperationAgent(), CashtroProject())              // Voltron continuous operation
	Worked(VoltronContinuousOperationAgent(), CashtroCatalogProject())       // Voltron continuous operation
	Worked(WordpressClientFactoryAgent(), CashtroProject())                  // WordPress client factory
	Worked(ZappierIntegrationAgent(), CashtroProject())                      // Zappier integration
}
